all:
  vars:
    confluent_license: 
    ansible_connection: ssh
    ansible_user: root
    repository_configuration: custom
    redhat_java_package_name: java-11-openjdk
    custom_yum_repofile_filepath: /root/confluent.repo
    kafka_broker_custom_properties:
      confluent.license: "{{ confluent_license }}"
    control_center_custom_properties:
      confluent.license: "{{ confluent_license }}"
    confluent_package_version: 6.2.1

zookeeper:
  hosts:
    kafka1.local:
    kafka2.local:
    kafka3.local:

kafka_broker:
  hosts:
    kafka1.local:
      broker_id: 1
    kafka2.local:
      broker_id: 2
    kafka3.local:
      broker_id: 3

control_center:
  hosts:
    kafka1.local:
